"""Interactive setup wizard for selecting Tuya devices to monitor."""

import questionary
from rich.console import Console
from rich.panel import Panel

from . import api_client
from . import devices as device_config
from . import setup as setup_module
from . import logger

log = logger.logs
console = Console()


def run_interactive_setup(path: str = "switches.toml", scan: bool = True) -> None:
    """Run an interactive wizard to select devices and write switches.toml.

    Devices already present in the existing switches.toml are pre-selected.
    """
    console.print(
        Panel.fit(
            "[bold blue]Tuya Device Setup[/bold blue]\n"
            "Fetching your devices from the Tuya Cloud...",
            border_style="blue",
        )
    )

    try:
        cloud_devices = api_client.get_devices()
    except Exception as exc:
        console.print(f"[red]Failed to fetch devices: {exc}[/red]")
        raise

    if not cloud_devices:
        console.print(
            "[yellow]No devices found in your Tuya Cloud project.[/yellow]\n"
            "Make sure you've linked your Smart Life app account."
        )
        return

    # Load existing config to pre-select already-monitored devices
    existing_switches = device_config.load_switches(path)
    existing_ids = {sw.get("id") for sw in existing_switches if sw.get("id")}
    if existing_ids:
        console.print(
            f"[dim]Pre-selected {len(existing_ids)} device(s) from existing {path}.[/dim]"
        )

    # Preserve existing IPs if cloud doesn't provide them
    existing_ips = {
        sw.get("id"): sw.get("ip", "") for sw in existing_switches if sw.get("id")
    }

    # Sort alphabetically by name
    sorted_devices = sorted(cloud_devices, key=lambda d: d.get("name", "").lower())

    console.print(f"\n[green]Found {len(sorted_devices)} device(s).[/green]\n")

    choices = []
    for dev in sorted_devices:
        name = dev.get("name", "Unnamed")
        dev_id = dev.get("id", "")
        display = (
            f"{name}  ({dev_id[:12]}...)" if len(dev_id) > 12 else f"{name}  ({dev_id})"
        )
        is_checked = dev_id in existing_ids
        choices.append(
            questionary.Choice(title=display, value=dev_id, checked=is_checked)
        )

    selected_ids = questionary.checkbox(
        "Select devices to monitor (space to toggle, type to filter):",
        choices=choices,
        instruction="Use arrow keys to navigate, space to select, enter to confirm.",
    ).ask()

    if selected_ids is None:
        console.print("[yellow]Cancelled. No changes made.[/yellow]")
        return

    if not selected_ids:
        console.print("[yellow]No devices selected. No changes made.[/yellow]")
        return

    local = setup_module.scan_local_network() if scan else {}

    lines = [
        "# Tuya Smart Switch Configuration",
        "# Auto-generated by 'tuya setup'",
        "# Run 'tuya setup' again to refresh or add new devices.",
        "",
    ]

    selected_set = set(selected_ids)
    for dev in sorted_devices:
        dev_id = dev.get("id", "")
        if dev_id not in selected_set:
            continue

        name = dev.get("name", "Unnamed")
        local_key = dev.get("key", "")
        version = dev.get("version", "3.3")
        ip = dev.get("ip", "")

        if not ip and dev_id in local:
            ip = local[dev_id].get("ip", "")

        # Preserve IP from existing config if still missing
        if not ip and dev_id in existing_ips:
            ip = existing_ips[dev_id]

        lines.append("[[switch]]")
        lines.append(f'id = "{dev_id}"')
        lines.append(f'name = "{name}"')
        lines.append(f'local_key = "{local_key}"')
        lines.append(f'ip = "{ip or ""}"')
        lines.append(f'version = "{version}"')
        lines.append("")

    content = "\n".join(lines) + "\n"

    with open(path, "w") as f:
        f.write(content)

    console.print(
        f"\n[green]Wrote {path}[/green] with {len(selected_ids)} device(s) enabled."
    )
    if any(
        not (
            dev.get("ip")
            or local.get(dev.get("id"), {}).get("ip")
            or existing_ips.get(dev.get("id"))
        )
        for dev in sorted_devices
        if dev.get("id") in selected_set
    ):
        console.print(
            "[yellow]Warning: some selected devices are missing local IPs.[/yellow]\n"
            "Edit switches.toml and fill in the 'ip' field for local control."
        )

    log.info(
        "Interactive setup complete",
        path=path,
        selected=len(selected_ids),
        total=len(sorted_devices),
    )
